### ISSUE TITLE
 GenServer.call(Bureaucrat.Recorder) not alive

### ISSUE THREAD

**Issue by cilim** [api-hogs/bureaucrat#35]
Hello 👋 

I updated the library to `0.2.1` and used the `ApiBlueprintWriter` and everything went smoothly. I have the API documentation generated and it's working well with aglio.

I just wanted to report that I got this error after everything was finished:

```
10:58:40.116 [error] GenServer #PID<0.4398.0> terminating
** (stop) exited in: GenServer.call(Bureaucrat.Recorder, :get_records, 5000)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir) lib/gen_server.ex:820: GenServer.call/3
    (bureaucrat) lib/bureaucrat/formatter.ex:20: Bureaucrat.Formatter.generate_docs/0
    (bureaucrat) lib/bureaucrat/formatter.ex:10: Bureaucrat.Formatter.handle_cast/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", {:suite_finished, 178304628, nil}}
Finished in 178.3 seconds
585 tests, 0 failures

Randomized with seed 750804
```

**Comment by cilim** [comment]
Disregard.
I figured out the problem and it originated in my application.

**Comment by hasitha** [comment]
@cilim I have the same problem after upgrading to Elixir 1.6.4. What did you change in your application to fix this?

**Comment by cilim** [comment]
@hasitha the newer versions of Elixir don't require to explicitly define the applications from the dependencies in the `mix.exs` file.

Instead of having this in the `mix.exs` file:

```
def application do
    [
      mod: {NameOfMyApp, []},
      applications: [
        :phoenix,
        :phoenix_pubsub,
        :cowboy,
        :logger
      ]
    ]
  end
```

you just need this:

```
def application do
    [mod: {NameOfMyApp, []}]
  end
```

Let me know if this the trick for you.

**Comment by Ziinc** [comment]
I seem to be still getting this error on elixir 1.8.2, with bureaucrat 0.2.5 and with mix.exs set up as :
```
def application do
    [mod: {NameOfMyApp, []}]
  end
```

Error message that comes up after the tests are run:
```
16:12:29.831 [error] GenServer #PID<0.484.0> terminating
** (stop) exited in: GenServer.call(Bureaucrat.Recorder, :get_records, 5000)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir) lib/gen_server.ex:979: GenServer.call/3
    (bureaucrat) lib/bureaucrat/formatter.ex:20: Bureaucrat.Formatter.generate_docs/0
    (bureaucrat) lib/bureaucrat/formatter.ex:10: Bureaucrat.Formatter.handle_cast/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", {:suite_finished, 6340217, nil}}
16:12:29.839 [error] Task #PID<0.471.0> started from #PID<0.93.0> terminating
** (stop) exited in: GenServer.stop(#PID<0.484.0>, :normal, 30000)
    ** (EXIT) exited in: :sys.terminate(#PID<0.484.0>, :normal, :infinity)
        ** (EXIT) exited in: GenServer.call(Bureaucrat.Recorder, :get_records, 5000)
            ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir) lib/gen_server.ex:948: GenServer.stop/3
    (ex_unit) lib/ex_unit/event_manager.ex:24: anonymous fn/2 in ExUnit.EventManager.stop/1
    (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ex_unit) lib/ex_unit/event_manager.ex:23: ExUnit.EventManager.stop/1
    (ex_unit) lib/ex_unit/runner.ex:28: ExUnit.Runner.run/2
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: &ExUnit.run/0
```
